import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from './Header'
import Test from './Test'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <Header/>
      <main className={styles.stuff}>
      <div>Test
      <Test/>
      </div>
      </main>

      <footer className={styles.footer}>
        <div>Footer</div>
      </footer>
    </div>
  )
}
